In [36]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression

In [37]:
X_train = np.load("X_train.npy")
y_train = np.load("y_train.npy")

X_val = np.load("X_val.npy")
y_val = np.load("y_val.npy")

X_test = np.load("X_test.npy")
y_test = np.load("y_test.npy")

## Logistic Regression

In [38]:
logistic_model = LogisticRegression(random_state=42)

In [39]:
logistic_model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [40]:
y_val_pred = logistic_model.predict(X_val)

In [42]:
from sklearn.metrics import accuracy_score

val_accuracy = accuracy_score(y_val, y_val_pred)
print("Validation Accuracy:", val_accuracy)

Validation Accuracy: 0.8888888888888888

In [43]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_val, y_val_pred)
print(cm)

[[5244  356]
 [ 444 1156]]

In [44]:
from sklearn.metrics import classification_report

print(classification_report(y_val, y_val_pred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93      5600
           1       0.76      0.72      0.74      1600

    accuracy                           0.89      7200
   macro avg       0.84      0.83      0.84      7200
weighted avg       0.89      0.89      0.89      7200

## K-Nearest Neighbors (KNN)

In [45]:
  from sklearn.neighbors import KNeighborsClassifier

In [46]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [47]:
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [48]:
y_val_pred_knn = knn_model.predict(X_val)

In [49]:
knn_accuracy = accuracy_score(y_val, y_val_pred_knn)
print("KNN Validation Accuracy:", knn_accuracy)

KNN Validation Accuracy: 0.8913888888888889

In [51]:
print(classification_report(y_val, y_val_pred_knn))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93      5600
           1       0.78      0.71      0.74      1600

    accuracy                           0.89      7200
   macro avg       0.85      0.83      0.84      7200
weighted avg       0.89      0.89      0.89      7200

## Support Vector Machine (SVM)

In [52]:
from sklearn.svm import SVC

In [53]:
svm_model = SVC(kernel="rbf", random_state=42)

In [54]:
svm_model.fit(X_train, y_train)

SVC(random_state=42)

In [55]:
y_val_pred_svm = svm_model.predict(X_val)

In [56]:
svm_accuracy = accuracy_score(y_val, y_val_pred_svm)
print("SVM Validation Accuracy:", svm_accuracy)

SVM Validation Accuracy: 0.9126388888888889

In [57]:
print(classification_report(y_val, y_val_pred_svm))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94      5600
           1       0.84      0.75      0.79      1600

    accuracy                           0.91      7200
   macro avg       0.89      0.85      0.87      7200
weighted avg       0.91      0.91      0.91      7200

## Model Evaluation & Comparison

In [58]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "KNN",
        "SVM"
    ],
    "Validation Accuracy": [
        val_accuracy,
        knn_accuracy,
        svm_accuracy
    ]
})

results

                 Model  Validation Accuracy
0  Logistic Regression             0.888889
1                  KNN             0.891389
2                  SVM             0.912639

# Hyperparameter

## Logistic Regression - Grid Search & Cross Validation

In [59]:
from sklearn.model_selection import GridSearchCV

In [60]:
param_grid_lr = {
    "C": [0.01, 0.1, 1, 10, 100],
    "solver": ["liblinear", "lbfgs"]
}

In [61]:
grid_lr = GridSearchCV(
    estimator=LogisticRegression(random_state=42),
    param_grid=param_grid_lr,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [62]:
grid_lr.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(random_state=42), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'solver': ['liblinear', 'lbfgs']},
             scoring='accuracy')

In [63]:
grid_lr.best_params_

{'C': 0.1, 'solver': 'liblinear'}

In [64]:
grid_lr.best_score_

np.float64(0.8970138888888888)

In [65]:
best_lr_model = grid_lr.best_estimator_

In [66]:
y_val_pred_lr_tuned = best_lr_model.predict(X_val)

In [67]:
tuned_lr_accuracy = accuracy_score(y_val, y_val_pred_lr_tuned)
print("Tuned Logistic Regression Validation Accuracy:", tuned_lr_accuracy)

Tuned Logistic Regression Validation Accuracy: 0.8890277777777778

In [68]:
print(classification_report(y_val, y_val_pred_lr_tuned))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93      5600
           1       0.77      0.72      0.74      1600

    accuracy                           0.89      7200
   macro avg       0.84      0.83      0.84      7200
weighted avg       0.89      0.89      0.89      7200

## K-Nearest Neighbors (KNN) - Grid Search & Cross Validation

In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
param_grid_knn = {
    "n_neighbors": [3, 5, 7, 9, 11],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]
}

In [71]:
grid_knn = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=param_grid_knn,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [72]:
grid_knn.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [73]:
grid_knn.best_params_

{'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'distance'}

In [74]:
grid_knn.best_score_

np.float64(0.9017361111111111)

In [75]:
best_knn_model = grid_knn.best_estimator_

In [77]:
y_val_pred_knn_tuned = best_knn_model.predict(X_val)

In [79]:
tuned_knn_accuracy = accuracy_score(y_val, y_val_pred_knn_tuned)
print("KNN Validation Accuracy:", tuned_knn_accuracy)

KNN Validation Accuracy: 0.8969444444444444

## Support Vector Machine (SVM) - Grid Search & Cross Validation

In [83]:
param_grid_svm = {
    "C": [0.1, 1, 10],
    "gamma": ["scale"],
    "kernel": ["rbf"]
}

In [84]:
grid_svm = GridSearchCV(
    estimator=SVC(random_state=42),
    param_grid=param_grid_svm,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [85]:
grid_svm.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=42), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'gamma': ['scale'],
                         'kernel': ['rbf']},
             scoring='accuracy')

In [86]:
grid_svm.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}

In [87]:
best_svm_model = grid_svm.best_estimator_

In [88]:
y_val_pred_svm_tuned = grid_svm.best_estimator_.predict(X_val)

In [89]:
tuned_svm_accuracy = accuracy_score(y_val, y_val_pred_svm_tuned)
print("SVM Validation Accuracy:", tuned_svm_accuracy)

SVM Validation Accuracy: 0.9131944444444444

In [90]:
tuned_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "KNN",
        "SVM"
    ],
    "Tuned Validation Accuracy": [
        tuned_lr_accuracy,
        tuned_knn_accuracy,
        tuned_svm_accuracy
    ]
})

tuned_results

                 Model  Tuned Validation Accuracy
0  Logistic Regression                   0.889028
1                  KNN                   0.896944
2                  SVM                   0.913194

In [91]:
y_test_pred_svm = grid_svm.best_estimator_.predict(X_test)

In [92]:
test_svm_accuracy = accuracy_score(y_test, y_test_pred_svm)
print("Final SVM Test Accuracy:", test_svm_accuracy)

Final SVM Test Accuracy: 0.9164444444444444